name: samples

on:
  push:
    branches:
      - master
    paths:
      - 'samples/**'
  workflow_dispatch:
jobs:
  windows-latest:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        sample: [
          'Actions',
          'CefToolWindow',
          'CodeInspections',
          'CodeVision',
          'ContextActions',
          'InlayHints',
          'Notifications',
          'OptionPages',
          'PostfixTemplates'
        ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            samples/${{ matrix.sample }}/build/gradle-jvm
            samples/${{ matrix.sample }}/packages
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ matrix.sample }}-${{ hashFiles('**/gradlew.bat', '**/*.csproj', '**/*.props', '**/gradle-wrapper.properties', '**/gradle.properties') }}
      - run: ./gradlew.bat :buildPlugin :testDotNet --no-daemon
        working-directory: samples/${{ matrix.sample }}
